### ISSUE TITLE
Create a website

### ISSUE THREAD

**Issue by secondtruth** [open-webtech/owta-community#6]
Replace the redirect to the GitHub org currently set up on owta.dev with a real website. We will use GitHub Pages to host the website.

## Tasks

- [ ] Find an appropriate existing design/template and adapt it to OWTA's needs and branding
- [ ] Create the needed website pages
  - [ ] About: Use the GitHub org's profile readme as text
- [ ] Set up GitHub Pages for hosting the website and set owta.dev as custom domain
- [ ] Develop an integrated publications section or a separate site
  - [ ] Integrate giscus for allowing visitor comments on publications
